spring.application.name=board

spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.datasource.url=jdbc:mariadb://localhost:3306/board?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=0722
spring.datasource.driverClassName=org.mariadb.jdbc.Driver

spring.thymeleaf.prefix=classpath:/templates/

file.dir=C:/shop

spring.thymeleaf.cache=false
